[package]
name = "arroy"
version = "0.1.0"
edition = "2021"

[dependencies]
annoy-rs = { path =  "../RuAnnoy" }
bytemuck = { version = "1.14.0", features = ["min_const_generics", "derive", "extern_crate_alloc"] }
byteorder = "1.5.0"
ordered-float = "4.1.1"
