[package]
name = "arroy"
description = "Annoy-inspired Approximate Nearest Neighbors in Rust, based on LMDB and optimized for memory usage"
version = "0.1.0"
documentation = "https://docs.rs/arroy"
repository = "https://github.com/meilisearch/arroy"
keywords = ["ANN-search", "Graph-algorithms", "Vector-Search", "Store"]
categories = ["algorithms", "database", "data-structures", "science"]
authors = ["Kerollmops <clement@meilisearch.com>", "Tamo <tamo@meilisearch.com>"]
license = "MIT"
edition = "2021"

[dependencies]
bytemuck = { version = "1.14.0", features = ["derive", "extern_crate_alloc"] }
byteorder = "1.5.0"
heed = { version = "0.20.0-alpha.9", default-features = false }
ordered-float = "4.1.1"
rand = { version = "0.8.5", features = ["alloc"] }
thiserror = "1.0.50"

[dev-dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.10", features = ["derive"] }
heed = { version = "0.20.0-alpha.9", default-features = false }
insta = "1.34.0"
instant-distance = "0.6.1"
rand = { version = "0.8.5", features = ["std_rng"] }
tempfile = "3.8.1"
