[package]
name = "arroy"
version = "0.1.0"
edition = "2021"

[dependencies]
annoy-rs = "0.1.0"
bytemuck = { version = "1.14.0", features = ["min_const_generics", "derive", "extern_crate_alloc"] }
byteorder = "1.5.0"
heed = "0.20.0-alpha.6"
ordered-float = "4.1.1"
rand = "0.8.5"
tempfile = "3.8.1"
